name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test base model
      id: test-base-model
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test base model
        setup-command: pip install -r requirements.txt
        command: python manage.py test thingproject.test-base-model
        timeout: 1
        max-score: 4
    - name: Test model
      id: test-model
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test model
        setup-command: pip install -r requirements.txt
        command: python manage.py test thingproject.test-model
        timeout: 4
        max-score: 14
    - name: Test view
      id: test-view
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test view
        setup-command: pip install -r requirements.txt
        command: python manage.py test thingproject.test-view
        timeout: 5
        max-score: 7
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-BASE-MODEL_RESULTS: "${{steps.test-base-model.outputs.result}}"
        TEST-MODEL_RESULTS: "${{steps.test-model.outputs.result}}"
        TEST-VIEW_RESULTS: "${{steps.test-view.outputs.result}}"
      with:
        runners: test-base-model,test-model,test-view
